logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    default:
      format: '%(asctime)s %(levelname)-1.1s %(process)d %(name)s:%(funcName)s:%(lineno)s | %(message)s'
    bare:
      format: '%(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: default
      filename: /var/log/chatter/chatter.log
      maxBytes: 10485760
      backupCount: 10
      encoding: utf-8
  root:
    handlers:
      - file
    level: INFO

notify:
    dingtalk_access_token: ${DINGTALK_ACCESS_TOKEN}
    dingtalk_secret:  ${DINGTALK_SECRET}

openai:
    api_key: ${OPENAI_API_key}
    user: ${OPENAI_USER}
    passwd: ${OPENAI_PASSWD}

users:
    - userid: 0356204035841823
      name: "杨勇"
      model: gpt3
    - userid: 0356204035841824
      name: "李四"
      model: gpt35
